export const DOUBLE_COUNTER = 'counter/DOUBLE_COUNTER';
export const CLICK_COUNTER = 'counter/CLICK_COUNTER';
export const INCREMENT_COUNTER = 'counter/INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'counter/DECREMENT_COUNTER';
export const INCREMENT_COUNTER_BY = 'counter/INCREMENT_COUNTER_BY';
export const DECREMENT_COUNTER_BY = 'counter/DECREMENT_COUNTER_BY';
export const INCREMENT_COUNTER_ASYNC = 'counter/INCREMENT_COUNTER_ASYNC';
export const DECREMENT_COUNTER_ASYNC = 'counter/DECREMENT_COUNTER_ASYNC';

export const VALUE = 'shared/VALUE';
export const UPDATE_VALUE = 'shared/UPDATE_VALUE';
export const MUTATE_UPDATE_VALUE = 'shared/MUTATE_UPDATE_VALUE';
export const MUTATE_UPDATE_VALUE_ASYNC = 'shared/MUTATE_UPDATE_VALUE_ASYNC';